### ISSUE TITLE
Errors now that our SSO server is in local

### ISSUE THREAD

**Issue by jonathanregalo** [ArchitectNow/cli#74]
How do you feel about adding:
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`
since this should only run local?

After adding Identity Server to our local, we had to switch everything to SSL on local and add certs. Error we are getting:
_Fetching from https://localhost:5301/client/v1/permissions/masterUnknown error: FetchError: request to https://localhost:5301/client/v1/permissions/master failed, reason: **unable to verify the first certificate**_

We already tried just adding https to the permissions.json: "url": "http**s**://localhost:5301/...

Here are a few related solutions:
https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired#answer-29397100

**Comment by jonathanregalo** [comment]
We did this locally and it did the trick. @LuizGsa21 Can you put this in?

`/cli/src/commands/permissions.ts`

```
  constructor(
    @inject(Logger) readonly _logger: Logger,
    @inject(CommandsMap) readonly _commandsMap: CommandMap,
  ) {
    super(_logger, _commandsMap, 'permissions');
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
  }
```

**Comment by LuizGsa21** [comment]
It would be better to set the environment variable before starting the program.

In the command line just do:

`NODE_TLS_REJECT_UNAUTHORIZED='0' myProgram`
